title: "Rizan's"
description: >-
  Rizan's personal website.
baseurl: ""
url: "https://rizanw.github.io/rzndwb"
repository: rizanw/rzndwb
github_username: rizanw
author:
  name: "Rizky Andre (Rizan) Wibisono"
  position: "Software Engineer"
  email: "rizkyandre.w@outlook.com"
  linkedin: "https://www.linkedin.com/in/rizan-wibisono/"
  instagram: "https://www.instagram.com/rzndwb"
  twitter: "https://x.com/rzndwb"
  blog: "https://rzndwb.medium.com"
  photo: "assets/images/rizanw.webp"
welfin:
  url: "https://welfin.rzndwb.xyz"
  icon: "assets/images/welfin.webp"
